cabal-version: 2.2
-- todo-manager.cabal
name: todo-manager
version: 0.1.0.0
description: A simple todo manager
category: CLI
build-type: Simple

common base-and-compiler-flags
  build-depends: base >=4.7 && <5
  ghc-options:
    -O2
    -Weverything

common beam-sqlite
  build-depends:
    beam-sqlite >=0.5.4.0 && <0.5.5,
    sqlite-simple >=0.4.19.0 && <0.4.20,

common text
  build-depends:
    text >=2.1.2 && <2.2,

common time
  build-depends:
    time >=1.12 && <1.13,

library
  import: base-and-compiler-flags, beam-sqlite, text, time
  hs-source-dirs: lib
  exposed-modules:
    TodoManager.Lenses
    TodoManager.Queries
    TodoManager.Schema
    TodoManager.Types
    TodoManager.Types.Constructors
    TodoManager.Types.Getters

  default-language: GHC2024
  build-depends:
    beam-core >=0.10.3.1 && <0.10.4,
    microlens >=0.4.14 && <0.4.15,
    transformers >=0.6.1.2 && <0.6.2,

  other-modules: TodoManager.Types.Internal

executable todo-manager-cli
  import: base-and-compiler-flags, beam-sqlite
  main-is: Main.hs
  hs-source-dirs: src
  default-language: GHC2024
  build-depends:
    directory >=1.3.9.0 && <1.4,
    filepath >=1.5.4.0 && <1.6,
    todo-manager,

  other-modules:
    Configuration

test-suite test
  import: base-and-compiler-flags, beam-sqlite, text, time
  default-language: GHC2024
  type:
    exitcode-stdio-1.0

  hs-source-dirs:
    test

  main-is:
    Main.hs

  build-depends:
    hspec >=2.11.11 && <2.12,
    tasty >=1.5.3 && <1.6,
    tasty-hspec >=1.2.0.4 && <1.2.1,
    todo-manager,
